#!/bin/bash


CPU=$(grep -m 1 "model name" /proc/cpuinfo | cut -d: -f2 | sed -e 's/^ *//' | sed -e 's/$//')
CPUS=$(grep -c ^processor /proc/cpuinfo)
STEP=$(grep -m 1 "stepping" /proc/cpuinfo | cut -d: -f2 | sed -e 's/^ *//' | sed -e 's/$//')
BOGO=$(grep -m 1 "bogomips" /proc/cpuinfo | cut -d: -f2 | sed -e 's/^ *//' | sed -e 's/$//')
OS=$(lsb_release -si)
ram=$(free -m | grep -oP '\d+' | head -n 1)
VER=$(uname -a )
uptime=$(</proc/uptime)
uptime=${uptime%%.*} bold=$(tput bold)
zile=$(( uptime/60/60/24 )) 
secunde=$(( uptime%60 ))
minute=$(( uptime/60%60 ))
ore=$(( uptime/60/60%24 ))
vid=$(lspci | grep VGA | cut -f5- -d ' ') 
DISK=$(df -h --total | grep total |awk '{ printf "" $2 "B\n\n" }')




sleep 1
echo "${CYN}--------------------------------------------------------------------------${WHI}" 
echo "${WHI}|                    ${WHI}  G1cu and Aczdreign                                |${WHI}"          
echo "${CYN}--------------------------------------------------------------------------${WHI}" 
sleep 1
echo "${CYN} ->${WHI} Loading Resurces... ${DGRN} 34% ${WHI}"
echo "${CYN} ->${WHI} Loading Resurces... ${DGRN} 68% ${WHI}"
echo "${CYN} ->${WHI} Loading Resurces... ${DGRN} 100%${WHI}"
echo ""
echo ""
echo "${CYN} ->${WHI} Resource Loaded... ${DGRN} 100%${WHI}"
echo ""
sleep 2
echo "${WHI}# ${CYN}CPU           ${CYN} -> ${WHI}${CPU}${RES}"             #${WHI}"
echo "${WHI}# ${CYN}CPU CORE      ${CYN} -> ${WHI}${CPUS}${RES}"            #${WHI}"
echo "${WHI}# ${CYN}Stepping      ${CYN} -> ${WHI}${STEP}${RES}"            #${WHI}"
echo "${WHI}# ${CYN}Bogomips      ${CYN} -> ${WHI}${BOGO}${RES}"            #${WHI}"
echo "${WHI}# ${CYN}Ram           ${CYN} -> ${WHI}${ram}MB  [1024MB = 1GB]" #${WHI}"
echo "${WHI}# ${CYN}GPU           ${CYN} -> ${WHI}${vid}"
echo "${WHI}# ${CYN}DISK SPACE    ${CYN} -> ${WHI}${DISK}"
echo "${WHI}# ${CYN}Versiune      ${CYN} -> ${WHI}${VER}"
echo "${WHI}# ${CYN}Uptime        ${CYN} -> ${WHI}${zile} Zile"
sleep 2
if ((${EUID:-0} || "$(id -u)")); then

  echo "${WHI}#${CYN} Drept de root  -> ${WHI}Nu ai""${WHI}                                 ${WHI}"
sleep 3
else
echo "${WHI}# ${CYN}Drept de root  -> ${WHI}Ai                                            ${WHI}"
fi
sleep 3
echo "${CYN}--------------------------------------------------------------------------${WHI}" 
echo "${WHI}|                   ${WHI}Incepem in 3 Secunde                                 |${WHI}"
echo "${CYN}--------------------------------------------------------------------------${WHI}" 
sleep 1
echo "${CYN} ->${WHI}3${WHI}"
sleep 1
echo "${CYN} ->${WHI}2${WHI}"
sleep 1
echo "${CYN} ->${WHI}1${WHI}"
sleep 1
perl v.py.1 
