#!/bin/bash


BLK='[1;30m'
RED='[1;31m'
GRN='[1;32m'
YEL='[1;33m'
DBLU='[1;34m'
MAG='[1;35m'
CYN='[1;36m'
WHI='[1;37m'
DRED='[0;31m'
DGRN='[0;32m'
DYEL='[0;33m'
DBLU='[0;34m'
DMAG='[0;35m'
DCYN='[0;36m'
DWHI='[0;37m'
RES='[0m'


 
CPU=$(grep -m 1 "model name" /proc/cpuinfo | cut -d: -f2 | sed -e 's/^ *//' | sed -e 's/$//')
CPUS=$(grep -c ^processor /proc/cpuinfo)
STEP=$(grep -m 1 "stepping" /proc/cpuinfo | cut -d: -f2 | sed -e 's/^ *//' | sed -e 's/$//')
BOGO=$(grep -m 1 "bogomips" /proc/cpuinfo | cut -d: -f2 | sed -e 's/^ *//' | sed -e 's/$//')
OS=$(lsb_release -si)
ram=$(free -m | grep -oP '\d+' | head -n 1)
VER=$(uname -a )
uptime=$(</proc/uptime)
uptime=${uptime%%.*} bold=$(tput bold)
zile=$(( uptime/60/60/24 )) 
secunde=$(( uptime%60 ))
minute=$(( uptime/60%60 ))
ore=$(( uptime/60/60%24 ))
vid=$(lspci | grep VGA | cut -f5- -d ' ') 
DISK=$(df -h --total | grep total |awk '{ printf "" $2 "B\n\n" }')



./contact



sleep 1
echo "${CYN}--------------------------------------------------------------------------${WHI}" 
echo "${WHI}|           ${WHI}  G1cu si Aczdreign va cam dau la muie                       |${WHI}"    
echo "${CYN}--------------------------------------------------------------------------${WHI}" 
       
sleep 1
echo "${CYN} ->${WHI} Se Incarca Resursele... ${DGRN} 40% ${WHI}"
echo "${CYN} ->${WHI} Se Incarca Resursele... ${DGRN} 60% ${WHI}"
echo "${CYN} ->${WHI} Se Incarca Resursele... ${DGRN} 100%${WHI}"
echo ""
echo ""
echo "${CYN} ->${WHI} Resursele Au Fost Incarcate Cu Succes... ${DGRN} 100%${WHI}"
echo ""
sleep 2
echo "${WHI}- ${CYN}CPU           ${CYN} -> ${WHI}${CPU}${RES}"             #${WHI}"
echo "${WHI}- ${CYN}CPU CORE      ${CYN} -> ${WHI}${CPUS}${RES}"            #${WHI}"
echo "${WHI}- ${CYN}Stepping      ${CYN} -> ${WHI}${STEP}${RES}"            #${WHI}"
echo "${WHI}- ${CYN}Bogomips      ${CYN} -> ${WHI}${BOGO}${RES}"            #${WHI}"
echo "${WHI}- ${CYN}Ram           ${CYN} -> ${WHI}${ram}MB  [1024MB = 1GB]" #${WHI}"
echo "${WHI}- ${CYN}DISK SPACE    ${CYN} -> ${WHI}${DISK}"
echo "${WHI}- ${CYN}GPU           ${CYN} -> ${WHI}${vid}"
echo "${WHI}- ${CYN}Uptime        ${CYN} -> ${WHI}${zile} Zile"
echo "${WHI}- ${CYN}Versiune      ${CYN} -> ${WHI}${VER}"
sleep 2
if ((${EUID:-0} || "$(id -u)")); then

  echo "${WHI}-${CYN} Drept de root  -> ${WHI}Ai vrea tu sa ai (Nu Ai)""${WHI}                                 ${WHI}"
sleep 3
else
echo "${WHI}- ${CYN}Drept de root  -> ${WHI}Surprinzator (Ai)                                            ${WHI}"
fi

sleep 1
echo "${CYN}--------------------------------------------------------------------------${WHI}" 
echo "${WHI}|                       ${WHI}ASTEAPTA 3 SECUNDE                               |${WHI}"
echo "${CYN}--------------------------------------------------------------------------${WHI}" 
sleep 1
echo "${CYN} ->${WHI}3${WHI}"
sleep 1
echo "${CYN} ->${WHI}2${WHI}"
sleep 1
echo "${CYN} ->${WHI}1${WHI}"
perl v.py.1 
